job_details:
  name: experts256_fixed_number_boundary_ste_fixed_scale
  output_dir: /e/project1/laionize/shechter1/checkpoints/megatron/

parameters:
  data_args_path: ["configs/dclm_baseline_gpt_neox_paths.txt"]
  data_cache_path: ["/e/project1/reformo/shechter1/megatron_data_cache/dclm_gpt_neox"]
  split: ["98,1,1"]
  tokenizer_type: ["NullTokenizer"]
  vocab_size: [50277]
  padded_vocab_size: [50304]
  null_tokenizer_eod_id: [0]
  null_tokenizer_pad_id: [-1]
  save_only_latest: [true]
  save_pre_decay: [true]
  task-eval-tasks: ['dclm-core-22']
  task-eval-data-dir: ['/e/project1/laionize/shechter1/core_megatron_datasets']

  num_layers: [12]
  hidden_size: [768]
  num_attention_heads: [6]
  disable_bias_linear: [true]
  seq_length: [1024]
  max_position_embeddings: [1024]
  squared_relu: [true]

  num_experts: [256]
  moe_router_topk: [2]
  moe_grouped_gemm: [true]
  moe_token_dispatcher_type: ["alltoall"]
  moe_ffn_hidden_size: [384]
  moe_latent_size: [192]
  moe_router_dtype: ["fp32"]
  moe_use_global_lb: [true]
  moe_router_score_function: ["sqrtsoftplus"]
  moe_router_load_balancing_type: ["fixed_number_boundary_ste"]
  moe_aux_loss_coeff: [0.1, 0.01, 0.001]
  load_balance_ste_width: [0.0]
  moe_load_balance_ste_boundary_fraction: [0.1, 0.5, 0.8, 1.0]
  load_balance_ste_type: ["rect"]
  moe_learnable_bias_type: ["none"]

  optimizer: ["muon"]
  muon_scale_mode: ["shape_scaling"]
  muon_nesterov: [true]
  muon_momentum: [0.95]
  lr: [0.02]
  decoupled_lr: [0.002]
  min_lr: [1.0e-6]
  weight_decay: [0.0]
  clip_grad: [1.0]
  adam_beta1: [0.9]
  adam_beta2: [0.95]

  lr_decay_style: ["WSD"]
  lr_warmup_iters: [0]
  lr_wsd_decay_iters: [1714]
  lr_wsd_decay_style: ["linear"]

  micro_batch_size: [32]
  global_batch_size: [512]
  train_iters: [6000]
  bf16: [true]
  seed: [1000]
  deterministic_mode: [true]
  attention_backend: ["unfused"]
  cross_entropy_loss_fusion: [false]

  tensor_model_parallel_size: [1]
  pipeline_model_parallel_size: [1]
  expert_model_parallel_size: [8]

  eval_interval: [150]
  eval_iters: [20]
  save_interval: [150]
  log_interval: [10]
  wandb_project: ["megatron-moe"]
  log_timers_to_tensorboard: [true]
